project:
  type: book

book:
  title: "Métodos analíticos"
  author: "Felipe González"
  chapters:
    - index.qmd
    - 01-introduccion.qmd
    - 02-modelos-graficos.qmd
    - 03-modelos-causales.qmd
    - 04-experimentos.qmd
    - 05-contrafactuales.qmd
    - 99-referencias.qmd
  appendices:
    - apendice-1.qmd
bibliography: referencias/book.bib

format:
  html:
    theme: journal
    lang: es
    font-size: 1.1em
    code-fold: false



